# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 23:27
from __future__ import unicode_literals

from django.db import migrations


def add_attributes(apps, schema_editor):
    model = apps.get_model("api", "FakeNewsLinkAttribute")
    model.objects.get_or_create(pk=1, defaults={"name": "False information in headline"})
    model.objects.get_or_create(pk=2, defaults={"name": "Misleading headline"})
    model.objects.get_or_create(pk=3, defaults={"name": "No linked sources"})
    model.objects.get_or_create(pk=4, defaults={"name": "Broken or incorrect source links"})
    model.objects.get_or_create(pk=5, defaults={"name": "Cited sources contradict article's information"})
    model.objects.get_or_create(pk=6, defaults={"name": "Information not covered by well-known news sources"})
    model.objects.get_or_create(pk=7, defaults={"name": "False math or numeric figures"})
    model.objects.get_or_create(pk=8, defaults={"name": "False quotations"})
    model.objects.get_or_create(pk=9, defaults={"name": "Incomplete quotations"})
    model.objects.get_or_create(pk=10, defaults={"name": "Misleadingly retouched photography"})
    model.objects.get_or_create(pk=11, defaults={"name": "Photography does not have valid attribution"})
    model.objects.get_or_create(pk=12, defaults={"name": "Photography re-used from irrelevant sources"})
    model.objects.get_or_create(pk=12, defaults={"name": "Unnamed author"})
    model.objects.get_or_create(pk=13, defaults={"name": "Author has no contact information"})
    model.objects.get_or_create(pk=14, defaults={"name": "Sensational or hyperbolic language"})
    model.objects.get_or_create(pk=15, defaults={"name": "Poor editing, spelling / grammar errors"})
    model.objects.get_or_create(pk=16, defaults={"name": "Use of ALL CAPS"})
    model.objects.get_or_create(pk=17, defaults={"name": "Overuse of exclamation points"})
    model.objects.get_or_create(pk=18, defaults={"name": "Typosquatting / URL hijacking"})


def remove_attributes(apps, schema_editor):
    model = apps.get_model("api", "FakeNewsLinkAttribute")
    model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161203_2326'),
    ]

    operations = [
        migrations.RunPython(add_attributes, remove_attributes),
    ]
